#!/bin/bash
## Stop mover if > 400 GB available on cache
## AUTHOR: Freender
## https://github.com/freender/mover_tunning_daysold/blob/main/mover_stop.sh


# Retention Variables
target_space="429496729600" # Minimum free space after which mover runs
target_space_human=$((target_space / 1024 / 1024 / 1024))  # Convert bytes to GB

# Share variables:
share_path='/mnt/cache/media' #Path to you share

PIDFILE="/var/run/mover.pid" #Mover PID file


# Functions
# This function calculates current free space on share
get_free_space() {
  free_space=`df $share_path | awk 'NR>1{print $4*1000}'`
  free_space_human=$((free_space / 1024 / 1024 / 1024))  # Convert bytes to GB
}

# Function to check if mover process is running
is_mover_running() {
  if [ ! -f $PIDFILE ] ; then
    echo "Mover process is not running."
    exit 0
  fi
  return $?
}

# Main Script

while is_mover_running; do
  get_free_space;

  # Exit if more then 400 GB available
  if [ $free_space -gt $target_space ]
  then    
    echo "Free space is more than 400GB. Stopping mover process."
    /usr/local/sbin/mover stop
    exit 0
  fi
  echo "Mover is running"
  echo "Target space: $target_space_human GB"
  echo "Free space: $free_space_human GB"
  echo "Sleep for a while before checking again"
  sleep 60
done
